version: '3.8'
services:
  db:
    image: postgres:16
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: krowty999
    ports:
      - "5433:5432"
    volumes:
      - ./migrations/init_scripts:/docker-entrypoint-initdb.d
      - auth-db-data:/var/lib/postgresql/data


  auth-service:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: authuser
      DB_PASSWORD: krowty999
      DB_NAME: authdb
      DB_PORT: 5432
    ports:
      - "8081:8081"

volumes:
  auth-db-data:
